### ISSUE TITLE
I can`t load version2019 dataset with PythonAPI

### ISSUE THREAD

**Issue by Lucksong** [youtubevos/cocoapi#1]
Hi, thanks to your work, but I encountered some problems.
I download version2019 video instance segmentation dataset from this link:https://competitions.codalab.org/competitions/20128#participate-get_data.
But the labels of json style are inconsistent with the format given on this web page.
For example, I open the valid.json with vscode and search ' "segmenation" ' keyword while there are no any results.
Then I tried to load data with PythonAPI, I modified the path parameter and run pycocoDemo.ipynb to load valid.json which was downloaded from https://drive.google.com/drive/folders/1VBeVXSf-HfrhyBurtu1xfGn6zQ-ALpjZ?usp=sharing, but I got this error:
```
print(len(coco.dataset['categories']))
print(coco.dataset['categories'][0]['id'])
print(len(coco.imgs))
catIds = coco.getCatIds(catNms=['person','dog','skateboard']);
print(type(catIds[0]))
imgIds = coco.getImgIds(catIds=catIds );
print(imgIds)
imgIds = coco.getImgIds(imgIds = [324158])
img = coco.loadImgs(imgIds[np.random.randint(0,len(imgIds))])[0]

40
1
0
<class 'int'>
[]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-25-021d63060e40> in <module>
      8 print(imgIds)
      9 imgIds = coco.getImgIds(imgIds = [324158])
---> 10 img = coco.loadImgs(imgIds[np.random.randint(0,len(imgIds))])[0]

/data/EventSegmentation/MaskTrackRCNN/cocoapi/PythonAPI/pycocotools/coco.py in loadImgs(self, ids)
    229             return [self.imgs[id] for id in ids]
    230         elif type(ids) == int:
--> 231             return [self.imgs[ids]]
    232 
    233     def showAnns(self, anns):

KeyError: 324158
```
Is there anything wrong with my operation? or the format is really different with the style on that web page?

**Comment by Lucksong** [comment]
The first line of the valid.json is :
{"info": {"description": "**YouTube-VOS**", "url": "https://youtube-vos.org/home", "version": "1.0", "year": 2018, "contributor": "ychfan", "date_created": "2019-04-11 00:18:45.652429"}, "licenses": [{"url": "https://creativecommons.org/licenses/by/4.0/", "id": 1, "name": "Creative Commons Attribution 4.0 License"}],
The json is for YouTube-VOS not YouTube-VIS?

**Comment by Nickchangqing** [comment]
Hello I have the same question. When I use the method to load the train.json in YTVIS as coco dataset,there is something wrong in it. KeyError: 'image_id. How do you load the json file
