### ISSUE TITLE
How to encode masks to the YouTubeVIS CodaLab format?

### ISSUE THREAD

**Issue by joakimjohnander** [youtubevos/cocoapi#2]
Hey,

Thank you for this work (and MaskTrackRCNN). I have generated masks as (height, width) PyTorch-BoolTensors and would like to evaluate them using the CodaLab evaluation page. Each segmentation seems to have the structure {'size': (height, width), 'counts': rle} where rle is an encoding of the mask. How do I convert my masks? I have tried:

>    import third_party.cocoapi.PythonAPI.pycocotools.mask as cocomask
>
>    \# mask is (height, width) torch.BoolTensor
>    mask = np.array(mask.cpu().numpy()[:, :, np.newaxis], order='F')
>    rle = cocomask.encode(mask)[0]
>    rle['counts'] = rle['counts'].decode()
>    return rle

Best regards,
Joakim

**Comment by Fengweinlpr** [comment]
Have you solved it？

**Comment by linjieyangsc** [comment]
Hi @joakimjohnander . Please refer to the encoding function here:
https://github.com/youtubevos/cocoapi/blob/master/PythonAPI/pycocotools/mask.py

**Comment by joakimjohnander** [comment]
Thanks linjieyangsc, that seems to work. I use
```
    import third_party.cocoapi.PythonAPI.pycocotools.mask as cocomask

    # mask is a size (height, width) torch.BoolTensor
    mask_asnp = np.array(mask.cpu().numpy()[:, :, np.newaxis], order='F')
    rle = cocomask.encode(mask_asnp)[0]
```
In the end I used the original cocoapi (and not this fork) as the encoding functionality seems to be exactly the same.
